---
title: "My first RMarkdown document"
author: "Kirill Müller"
date: "11/30/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
library(tidyverse)
library(nycflights13)
knitr::opts_chunk$set(echo = TRUE)
```

## A table

```{r table1, echo = FALSE}
table1 %>% 
  knitr::kable()
```

This table has `r nrow(table1)` rows.

## A table as DT

```{r table1-2, echo = FALSE}
airports %>% 
  DT::datatable()
```

## A plot

```{r plot-static}
mpg %>% 
  ggplot() +
  geom_point(aes(displ, hwy))
```


## An interactive plot

```{r plot-dynamic}
p <-
  mpg %>% 
  ggplot() +
  geom_point(aes(displ, hwy))

plotly::ggplotly(p)
```

```{r plot-dynamic-surround}
plotly::ggplotly(
  mpg %>% 
    ggplot() +
    geom_point(aes(displ, hwy))
)
```

## An interactive map

```{r leaflet}
library(leaflet)
quakes %>% 
  head(50) %>% 
  leaflet() %>% 
  addTiles() %>% 
  addCircles()
```

## An interactive map with Google Earth tiles

Source: https://stackoverflow.com/a/43200650/946850

```{r}
library(leaflet)
quakes %>% 
  head(50) %>% 
  leaflet() %>% 
  addTiles(
    urlTemplate = "https://mts1.google.com/vt/lyrs=s&hl=en&src=app&x={x}&y={y}&z={z}&s=G",
    attribution = "Google"
  ) %>% 
  addCircles(popup = ~mag, color = "white")
```

## An interactive map with Google Maps tiles

Source: https://stackoverflow.com/a/43200650/946850

```{r}
library(leaflet)
quakes %>% 
  head(50) %>% 
  leaflet() %>% 
  addTiles(
    urlTemplate = "https://mt0.google.com/vt/lyrs=m&hl=en&x={x}&y={y}&z={z}&s=Ga",
    attribution = "Google"
  ) %>% 
  addCircles(popup = ~mag, color = "red")
```
